### PR TITLE
[69330] codeblock crash on tap

### PR DESCRIPTION
**Pull request by Willyfrog**
#### Summary

Fixes MM-69330 — tapping a code block crashes the app (regression in v2.41, worked in v2.40).

`CodeRoute` (`app/routes/(authenticated)/code.tsx`) read **every** route param through
`usePropsFromParams`, which runs `safeParseJSON` over each value. A code block whose text
happens to be valid JSON — e.g. `42`, `{"a":1}`, `[1,2,3]`, `true` — was therefore coerced
from a string into a number/object/boolean. `CodeScreen` passed that to the `Highlighter`,
whose `getMaximumLineLength` calls `code.split('\n')` on a non-string value, throwing
`TypeError: code.split is not a function` — the `Highlighter → CodeScreen → CodeRoute`
crash in the ticket's stack trace.

Plain code (not JSON-parseable) was unaffected, which is why this slipped through.

## Fix

Read `code` directly via `useLocalSearchParams` so it stays a raw string and never hits
`safeParseJSON`. `usePropsFromParams` is kept for the remaining props (`textStyle` is a real
object param that still needs JSON parsing).

## Tests

Added `app/routes/(authenticated)/code.test.tsx`: renders the real
`CodeRoute → CodeScreen → Highlighter` with controlled params (stubbing only the third-party
`react-syntax-highlighter`, since the crash is in our own code that runs before it renders).
Covers four JSON-parseable code-block contents plus a plain-code control.

- Fails against the buggy route (4× `code.split is not a function`).
- Passes with this fix (5/5).
- `eslint` clean; full `tsc --noEmit` reports 0 errors.

## Follow-up (not in this PR)

The root cause is an asymmetry in the navigation plumbing: `propsToParams`
(`app/screens/navigation.ts`) passes strings through raw while JSON-stringifying non-strings,
but `usePropsFromParams` runs `safeParseJSON` on everything. So **any** JSON-shaped string
param can be silently coerced — `code` is just the first field where it reaches a hard crash.
Other call sites that pass free-text strings (e.g. `agents_rewrite_options.originalMessage`,
channel `displayName`s) carry the same latent risk. Recommend a separate PR to make
encode/decode symmetric (always stringify ↔ always parse). 

Suggested options for doing this:

1 — Symmetric matched pair (recommended)

Producer always JSON.stringify (including strings); consumer always JSON.parse. Then '42' → '"42"' → '42' (stays a string); everything round-trips losslessly.
- Smallest core change: two one-line edits (the two functions above).
- Most principled: kills the entire bug class, types stop lying.

2 — Explicit parse intent (lower blast radius, more verbose)

Leave the producer; give the consumer a per-key opt-out: usePropsFromParams<T>({raw: ['code']}). Each route with a free-text string field declares it raw.
- No producer change, but requires per-route judgment and touches every affected call site.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-69330

#### Checklist

- [x] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.
- [ ] Have run E2E tests by adding label `E2E/Run` (or `E2E/Run-iOS` / `E2E/Run-Android` for platform-specific runs).

#### Device Information
This PR was tested on: iosSim

#### Release Note

```release-note
NONE
```

### CODE REVIEW

File: app/routes/(authenticated)/code.test.tsx [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+    useNavigation: () => ({
+        setOptions: jest.fn(),
+        addListener: jest.fn(() => jest.fn()),
+    }),
+    useRouter: () => ({
+        canGoBack: jest.fn(() => true),
+    }),
+}));
+
+describe('CodeRoute (MM-69330)', () => {
```
Comment (Willyfrog) [inline app/routes/(authenticated)/code.test.tsx:49]: I'm not 100% sure of keeping the tests, it was useful to make sure the AI fixed the right thing, but I feel there is little value in this tests after that.

**Review by enahum — APPROVED** [review]
